language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements_dev.txt
  - pip install coveralls

# commands to run tests
script:
  - '[ "$TRAVIS_PYTHON_VERSION" != "2.6" ] && python -m setup check -r -s || true'
  - flake8
  - pep257
  - nosetests
  - python -m setup install
  - '[ "$TRAVIS_PYTHON_VERSION" != "2.6" ] && python -m pyoath --help || true'

# upload coverage data to coveralls.io
after_success:
  - coveralls
